[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/nginx/access.log
    Tag               nginx.access
    Refresh_Interval  5

[OUTPUT]
    Name  opensearch
    Match *
    Host  opensearch
    Port  9200
    Index nginx-logs
    Suppress_Type_Name On